name: atn-tools
dependencies:
    - python=3.5
    - numpy
    - scipy
    - matplotlib
    - jupyter
    - pandas
    - networkx
    - h5py
    - pytest
    - cached-property
    - scikit-learn
    - graphviz
    - pip:
        - pydotplus
        - pygraphviz
